/*
 * @Author: jwj
 * @Date: 2023-07-24 21:08:01
 * @LastEditors: jwj
 * @LastEditTime: 2023-07-24 22:57:18
 */
import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import Template from './template'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Template>{children}</Template>
        <Footer />
      </body>
    </html>
  );
}
